// src/constants/blog/BlogData.ts
import { BlogPost } from '@/types/blog/BlogTypes';

export const blogPosts: BlogPost[] = [
  {
    id: '1',
    title: 'The Real Product From The Buyers Improvements In Overflow Basis.',
    slug: 'real-product-buyers-improvements',
    coverImage: 'https://images.pexels.com/photos/3183183/pexels-photo-3183183.jpeg',
    author: { id: '1', name: 'Daniel Roberts', avatar: 'https://randomuser.me/api/portraits/men/32.jpg' },
    date: 'April 03, 2023',
  },
  {
    id: '2',
    title: 'Why You Should Launch Your Product In Phases Not After Done',
    slug: 'launch-product-in-phases',
    coverImage: 'https://images.pexels.com/photos/3182812/pexels-photo-3182812.jpeg',
    author: { id: '2', name: 'Benjamin', avatar: 'https://randomuser.me/api/portraits/men/43.jpg' },
    date: 'April 04, 2023',
  },
  {
    id: '3',
    title: "Three Reasons You DON'T Need An App On The App Store",
    slug: 'reasons-dont-need-app-store',
    coverImage: 'https://images.pexels.com/photos/3182781/pexels-photo-3182781.jpeg',
    author: { id: '3', name: 'Darren Robertson', avatar: 'https://randomuser.me/api/portraits/men/46.jpg' },
    date: 'April 03, 2023',
  },
  {
    id: '4',
    title: 'Virtual Reality for Training: Companies Onboard Smarter',
    slug: 'virtual-reality-training-onboarding',
    coverImage: 'https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg',
    author: { id: '4', name: 'Daniel Mitchell', avatar: 'https://randomuser.me/api/portraits/men/44.jpg' },
    date: 'March 22, 2023',
  },
  {
    id: '5',
    title: 'Internal Mobility: Leverage Hidden Talent in Your Company',
    slug: 'internal-mobility-hidden-talent',
    coverImage: 'https://images.pexels.com/photos/3183171/pexels-photo-3183171.jpeg',
    author: { id: '5', name: 'Esther Howard', avatar: 'https://randomuser.me/api/portraits/women/44.jpg' },
    date: 'March 15, 2023',
  },
  {
    id: '6',
    title: 'Interoperation with Slack: What It Means for Your Workflow',
    slug: 'interoperation-with-slack',
    coverImage: 'https://images.pexels.com/photos/3205567/pexels-photo-3205567.jpeg',
    author: { id: '6', name: 'Conclude Team', avatar: 'https://randomuser.me/api/portraits/men/54.jpg' },
    date: 'March 10, 2023',
  },{
  id: '7',
  title: 'How AI is Revolutionizing Customer Support',
  slug: 'ai-revolutionizing-customer-support',
  coverImage: 'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg',
  author: { id: '7', name: 'Sophia Lee', avatar: 'https://randomuser.me/api/portraits/women/68.jpg' },
  date: 'April 10, 2023',
},
{
  id: '8',
  title: 'The Future of Remote Work: Trends to Watch',
  slug: 'future-of-remote-work-trends',
  coverImage: 'https://images.pexels.com/photos/3184287/pexels-photo-3184287.jpeg',
  author: { id: '8', name: 'Michael Johnson', avatar: 'https://randomuser.me/api/portraits/men/52.jpg' },
  date: 'April 12, 2023',
},
{
  id: '9',
  title: 'Top Strategies for Effective Time Management',
  slug: 'top-strategies-time-management',
  coverImage: 'https://images.pexels.com/photos/3184290/pexels-photo-3184290.jpeg',
  author: { id: '9', name: 'Emma Davis', avatar: 'https://randomuser.me/api/portraits/women/55.jpg' },
  date: 'April 14, 2023',
},
{
  id: '10',
  title: 'Sustainable Business Practices for the Modern Company',
  slug: 'sustainable-business-practices',
  coverImage: 'https://images.pexels.com/photos/3184405/pexels-photo-3184405.jpeg',
  author: { id: '10', name: 'Liam Brown', avatar: 'https://randomuser.me/api/portraits/men/60.jpg' },
  date: 'April 15, 2023',
},
{
  id: '11',
  title: 'Boost Your Productivity with These Simple Hacks',
  slug: 'boost-productivity-simple-hacks',
  coverImage: 'https://images.pexels.com/photos/3184295/pexels-photo-3184295.jpeg',
  author: { id: '11', name: 'Olivia Martinez', avatar: 'https://randomuser.me/api/portraits/women/66.jpg' },
  date: 'April 17, 2023',
},
{
  id: '12',
  title: 'The Impact of Blockchain on Modern Business',
  slug: 'impact-blockchain-modern-business',
  coverImage: 'https://images.pexels.com/photos/3184463/pexels-photo-3184463.jpeg',
  author: { id: '12', name: 'Ethan Clark', avatar: 'https://randomuser.me/api/portraits/men/61.jpg' },
  date: 'April 18, 2023',
},
{
  id: '13',
  title: 'Building Inclusive Teams: Why It Matters',
  slug: 'building-inclusive-teams',
  coverImage: 'https://images.pexels.com/photos/3183198/pexels-photo-3183198.jpeg',
  author: { id: '13', name: 'Maya Wilson', avatar: 'https://randomuser.me/api/portraits/women/62.jpg' },
  date: 'April 20, 2023',
},
{
  id: '14',
  title: 'Cybersecurity Essentials for Small Businesses',
  slug: 'cybersecurity-essentials-small-businesses',
  coverImage: 'https://images.pexels.com/photos/3183150/pexels-photo-3183150.jpeg',
  author: { id: '14', name: 'Noah Anderson', avatar: 'https://randomuser.me/api/portraits/men/59.jpg' },
  date: 'April 22, 2023',
},
{
  id: '15',
  title: 'How to Leverage Data Analytics for Growth',
  slug: 'leverage-data-analytics-growth',
  coverImage: 'https://images.pexels.com/photos/3183182/pexels-photo-3183182.jpeg',
  author: { id: '15', name: 'Ava Thompson', avatar: 'https://randomuser.me/api/portraits/women/64.jpg' },
  date: 'April 25, 2023',
},

];
